### ISSUE TITLE
Implement test case(s) for JsonReader::doPeek

### ISSUE THREAD

**Issue by kittytinythai** [DD2480-2021-group-22/gson#2]
Implement test cases to achieve 100% branch coverage.
`JsonReader::doPeek@460-594@./com/google/gson/stream/JsonReader.java`

**Comment by binsu-kth** [comment]
Seem to have 100% branch coverage already, when counting for Jacoco bug.

**Comment by grundb** [comment]
Closed because the decision was made to choose methods individually.
