### ISSUE TITLE
Implement test case(s) for JsonReader::nextNonWhitespace

### ISSUE THREAD

**Issue by kittytinythai** [DD2480-2021-group-22/gson#3]
Implement test cases to achieve 100% branch coverage.
`JsonReader::nextNonWhitespace@1312-1399@./com/google/gson/stream/JsonReader.java`

**Comment by binsu-kth** [comment]
Seem to have 100% coverage already, when counting for Jacoco bug.

**Comment by grundb** [comment]
Closed because the decision was made to choose methods individually.
