### ISSUE TITLE
Implement test case(s) for JsonReader::readEscapeCharacter

### ISSUE THREAD

**Issue by kittytinythai** [DD2480-2021-group-22/gson#4]
Implement test cases to achieve 100% branch coverage.
`JsonReader::readEscapeCharacter@1497-1555@./com/google/gson/stream/JsonReader.java`

**Comment by binsu-kth** [comment]
Already have 100% branch coverage when counting for Jacoco throw exception bugs.

**Comment by grundb** [comment]
Closed because the decision was made to choose methods individually.
