### ISSUE TITLE
Implement test case(s) for ISO8601Utils::parse

### ISSUE THREAD

**Issue by kittytinythai** [DD2480-2021-group-22/gson#5]
Implement test cases to achieve 100% branch coverage.
`ISO8601Utils::parse@123-277@./com/google/gson/internal/bind/util/ISO8601Utils.java`

**Comment by binsu-kth** [comment]
Tests are implemented in the method testIncreaseCoverageParseMethod in src/test/java/com/google/gson/DefaultDateTypeAdapterTest.java.

**Branch coverage** before: 67% including Jacoco bug of not counting exceptions.
**Brach coverage** after implementing two tests for uncovered switch cases: 70%
(Note: Jacoco doesn't report coverage for custom thrown exceptions)

**Comment by binsu-kth** [comment]
Brach coverage after implementing two tests for uncovered switch cases: 70%

**Comment by binsu-kth** [comment]
Tests are implemented in the method _testIncreaseCoverageParseMethod_ in  src/test/java/com/google/gson/DefaultDateTypeAdapterTest.java.
