### ISSUE TITLE
Implement test case(s) for Excluder::excludeField

### ISSUE THREAD

**Issue by kittytinythai** [DD2480-2021-group-22/gson#6]
Implement test cases to achieve 100% branch coverage.
`Excluder::excludeField@151-191@./com/google/gson/internal/Excluder.java`

**Comment by binsu-kth** [comment]
Before implementation: 96% branch coverage.

**Comment by binsu-kth** [comment]
Local or anonymous class. Might be impossible conditions to test.

**Comment by grundb** [comment]
Closed because the decision was made to choose other functions.
